### ISSUE TITLE
Saysomething broken

### ISSUE THREAD

**Issue by schmichael** [yougov/pmxbot#44]
Getting an exception from saysomething when starting pmxbot:

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pmxbot/pmxbotenv/lib/python3.4/site-packages/pmxbot/saysomething.py", line 105, in init_class
    cls.markov_data = markov_data_from_words(words)
  File "/home/pmxbot/pmxbotenv/lib/python3.4/site-packages/pmxbot/saysomething.py", line 31, in markov_data_from_words
    for word in words:
  File "/home/pmxbot/pmxbotenv/lib/python3.4/site-packages/pmxbot/saysomething.py", line 68, in words_from_lines
    words = line.strip().lower().split()
AttributeError: 'tuple' object has no attribute 'strip'
```

I've been carting around a pretty old sqlite db in case that makes any difference.

Output of `pip list`:

```
backports.method-request (1.0)
beautifulsoup4 (4.4.1)
CherryPy (5.1.0)
feedparser (5.2.1)
inflect (0.2.5)
irc (14.1)
jaraco.apt (1.0)
jaraco.classes (1.3)
jaraco.collections (1.3.2)
jaraco.compat (1.2)
jaraco.context (1.5.2)
jaraco.functools (1.11)
jaraco.itertools (1.7.1)
jaraco.logging (1.3.1)
jaraco.text (1.6.3)
jaraco.timing (1.2.2)
Jinja2 (2.8)
MarkupSafe (0.23)
more-itertools (2.2)
pip (8.1.1)
pmxbot (1113.6)
pytz (2016.3)
PyYAML (3.11)
requests (2.9.1)
setuptools (20.6.7)
six (1.10.0)
tempora (1.4)
wheel (0.29.0)
wordnik-py3 (2.1.2)
yg.lockfile (2.1.1)
zc.lockfile (1.1.0)
```

Ubuntu 15.10, Python 3.4.3+

:heart:

**Comment by lbolla** [comment]
Hi @schmichael!
I've pushed a fix in https://github.com/yougov/pmxbot/commit/a5da1fd878a7eaa57bc02077aee71a2fe5b9e6e5
Can you please pull and try again?

**Comment by schmichael** [comment]
Doesn't look like that fixed it:

```
pip install --upgrade git+https://github.com/yougov/pmxbot.git
...
Successfully installed pmxbot-1113.7.dev2+nga5da1fd

pmxbot config.yaml
...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pmxbot/pmxbotenv/lib/python3.4/site-packages/pmxbot/saysomething.py", line 105, in init_class
    cls.markov_data = markov_data_from_words(words)
  File "/home/pmxbot/pmxbotenv/lib/python3.4/site-packages/pmxbot/saysomething.py", line 31, in markov_data_from_words
    for word in words:
  File "/home/pmxbot/pmxbotenv/lib/python3.4/site-packages/pmxbot/saysomething.py", line 68, in words_from_lines
    words = line.strip().lower().split()
AttributeError: 'tuple' object has no attribute 'strip'
```

**Comment by lbolla** [comment]
Can you try removing `pmxbot.sqlite`, if you have it in the root dir, or change `config.yaml` to point to a non-existing sqlite db? I suspect the issue there.
Alternatively, you can try to comment out either `words_from_logger` or `words_from_quotes` in `saysomething.py:words_from_logger_and_quotes` and see if you manage to make it work.
If you can't pinpoint the issue, it'd be great if you could share your settings, so that I am able to reproduce the issue here, 'cause at the moment I can't.

**Comment by schmichael** [comment]
An empty database fixed it, but probably because there was no data to trigger the error?

The schemas were the same, so I don't think it's a schema issue.

**Comment by lbolla** [comment]
@schmichael I managed to reproduce the error you are getting by inserting a row with an empty quote in the sqlite DB. Can you please verify that you have rows with quote=null in your DB?
I will push a fix for that, anyway.

**Comment by lbolla** [comment]
See https://github.com/yougov/pmxbot/commit/0af3f498bc228ad051fb0530f3f509b1d0234076

**Comment by schmichael** [comment]
Nope, no quotes with quote=null or library=null, and no logs with message=null. Upgraded to latest code and still get the error.

**Comment by lbolla** [comment]
Given that we already verified that it works with and empty sqlite DB, it'd be useful if you added some print statements in quotes.py:__iter__:90 to figure out which row is failing.
