### ISSUE TITLE
pmxbot should reply with messages inside a thread

### ISSUE THREAD

**Issue by sd2k** [yougov/pmxbot#50]
Slack's [best practices](https://api.slack.com/docs/message-threading#best_practices) for threads and bots recommend that bots reply within a thread if the original message is part of a thread. The new version of `python-slackclient` (v1.0.5) allows this by supplying the `thread` parameter (supplied as `thread_ts` in the incoming message object) to `channel.send_message`.

It looks like `pmxbot.Bot` expects each message to be a simple string; perhaps it could allow some additional context (the thread, in this case) to be passed from `handle_message` through to `transmit`? It would mean adding a `context` parameter to `handle_action`, `_handle_output`, `out`, and `transmit` I think.

**Comment by jaraco** [comment]
Yes, that sounds perfectly reasonable. Would you consider drafting an implementation?

**Comment by sd2k** [comment]
Sure, I'll aim to take a look at this on the weekend.
